### PR TITLE
Fix deleting old backups on remote drives + log error

### PR DESCRIPTION
**Pull request by AnonTester**

### CODE REVIEW

**Comment by robweber** [comment]
Thanks for the PR. 

As far as the original error this was only happening on remote drives? Did it matter if you used the browse dialog or the type your own path option when setting up the remote? Just want to make sure I do valid tests on this to repeat the original issue. 

Appreciate you taking the time.

**Comment by AnonTester** [comment]
Actually, I'm not sure if it's limited to remote drives. self.remote_base_path was missing the forward slash at the end resulting in the path and the file to be merged and therefore the file couldn't be deleted as it wasn't found. self.remote_vfs.root_path has the trailing slash and the removal of the files worked fine on my system with this change. 
I'm using compressed archives on a remote samba filesystem on Kodi 19 nightly (Linux) and didn't do any other tests.

**Comment by robweber** [comment]
That makes sense. The ```vfs.root_path``` variable is checked for the ending slash when the Class is made. Thanks!

**Comment by robweber** [comment]
I had to make a small fix to what you were trying to accomplish here. The ```vfs.root_path``` variable was actually one level too deep. This gets assigned during the backup process to the [root directory + the current backup directory](https://github.com/robweber/xbmcbackup/blob/master/resources/lib/backup.py#L355). The ```base_path``` variable is what was needed here, except for the pathing issues that you pointed out. I [created a function ](https://github.com/robweber/xbmcbackup/commit/e63560f0c43e89bbd2309462cc0078647c9854ad)to clean up the base path string as part of the backup rotation. 

Thanks for pointing this out!

**Comment by AnonTester** [comment]
Glad I could help and thanks for providing and supporting this addon. It's been a life saver a couple of times already.

**Pull request merged**
